language: go

go:
  - "1.11.x"
  - "1.12.x"
  - "master"

matrix:
  allow_failures:
    - go: "master"

  fast_finish: true

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/) # All the .go files, excluding vendor/
  - go get honnef.co/go/tools/cmd/staticcheck                   # Badass static analyzer/linter
  - go get github.com/fzipp/gocyclo
  - go get github.com/mitchellh/gox
  - go get github.com/golang/dep/cmd/dep

script:
  - dep init                                 # fetch any dependencies
  - test -z $(gofmt -s -l $GO_FILES)         # Fail if a .go file hasn't been formatted with gofmt
  - go test -v -race ./...                   # Run all the tests with the race detector enabled
  - go vet ./...                             # go vet is the official Go static analyzer
  - staticcheck ./...                          # "go vet on steroids" + linter
  - gocyclo -over 19 $GO_FILES               # forbid code with huge functions
  - make release                             # build release binaries

deploy:
  provider: releases
  api_key:
    secure: L8IVtFO79nudHduPadGnbgUHq45GQYIAS1Xq7uOiZch11wi+awohf4ZL0lSGn04ntUKCyAdPbYQjOq8j5K3YDMYS2yAOnA/OhzjRWsgA64juPT5OD96ONY5b1FruwQdjQbKKmbXHZLfQWsdqKKWb/8/jgIltc2ABuhI0oMAUg7LJqDv0CUbY705eSPn7cCKG1EKCurEEQyB4+qLN02VmZmzh6GSkkGebqe/TcwlAhlc9Q0AIf3i4BAVfmsgjdtuUXsvWFu6za/W5qDyNhDPFqFV8N6HU4dWM2IiXY4Sy+HRhhgTqnAGtv06pvDaCf93BVGHTCaSEMD6yTZkhqZsErtpGBQcqWwOHw61eXcxA7b0uYkLMjWdumfqHEkQpux1Ie3NVjnPXkrXmGUyGmx0xv6QGhOR+PozQlCR1LS6Pl6t68+p9lsxPn2CvSf6nwqSDQHy3M6J2DIHpfciO1wRY+fXKHK/SQiW08VAHhKLmMvdNeRpDlobeFq9dOuRss3Mqv0G7qfGv4A4fxKbc+HGl+yzcMxrehVQV6w31gvAgbYu2878WVr805VAMtpm5pFIHPDw6PPFoS5xMEhzSFgZwg884SkJBInGtPg9B3haS3Kx9d3aQOO8K7obpRxMPbj7dI9AB8+ZXukLSKPl7HIS2dwC8BS223kKXp4+uV6PQk2A=
  file_glob: true
  file: 'bin/defang_*' 
  skip_cleanup: true
  on:
    repo: jakewarren/defang
    tags: true
